### PR TITLE
Api branch

### PR DESCRIPTION
**Pull request by soesandarwin2201**
## What does this PR do?
This PR is raised to create a React front-end with a Rails back-end and connect them to display a random message.

## Description of the task to be completed

- [x] Create a new Rails API app called 'hello-rails-back-end'.
- [x] Initialize your project with Git.
- [x] Make sure that your project has a Postgres database set up.
- [x] Create a table for storing your messages and create 5 different greetings.
- [x] Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).

## How should it be tested
Clone the repository
```
git clone https://github.com/soesandarwin2201/hello-rails-backend
```
Navigate to the folder
```
cd hello-rails-backend
```
Checkout the branch
```
git checkout api-branch
```
Frontedn link 

git clone https://github.com/soesandarwin2201/hello-rails-frontend

#### Thanks for reviewing my PR :blush:

### CODE REVIEW

**Review by afanimartin — CHANGES_REQUESTED** [review]
Hi @soesandarwin2201, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that lacks a link to the frontend repo in the readme file. The frontend repo also lacks a link back to the backend repo in the readme file. 
Don't forget to use a professional readme file in the frontend repo. Please make these changes and resubmit.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by soesandarwin2201** [comment]
@afanimartin i have already add the readme file and the links in the api-branch and ui-branch , not in the dev branch. should i do that in the dev branch?

**Comment by afanimartin** [comment]
Am sorry if I missed it. I only saw the link in the pr description of the
backend repo. Make sure it's added to the readme file as well. Do this for
both repositories.

**Review by afanimartin — APPROVED** [review]
Hi @soesandarwin2201, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Professional readme files used in both repositories 
- Links to repo added in the respective readme files
- Both apps work as required

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
